name: deploy
on: [push]
defaults:
  run:
    working-directory: ./
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python dependencies
        run: |
          sed -i '/pkg-resources/d' requirements.txt
          pip install -r requirements.txt
          cd bin/dropbox
          mv settings.py.sample settings.py

      - name: install js dependencies
        run: npm install

  etl:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: extract
        run: ./extract.py
