name: deploy
on: [push]
jobs:
  necokecteni:
    runs-on: ubuntu-latest
    env:
      DROPBOX_TOKEN: ${{secrets.DROPBOX_TOKEN}}
      DROPBOX_FOLDER_ID: ${{secrets.DROPBOX_FOLDER_ID}}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python dependencies
        run: |
          sed -i '/pkg-resources/d' requirements.txt
          pip install -r requirements.txt
          cd bin/dropbox
          mv settings.py.sample settings.py

      - name: install js dependencies
        run: npm install

      - name: extract
        env:
          PELICAN_TEMP_FOLDER: ${{github.workspace}}/temp
          PELICAN_CONTENT_FOLDER: ${{github.workspace}}/content
        run: ${{github.workspace}}/bin/dropbox/extract.py

      - name: load
        env:
          PELICAN_TEMP_FOLDER: ${{github.workspace}}/temp
          PELICAN_CONTENT_FOLDER: ${{github.workspace}}/content
        run: ${{github.workspace}}/bin/dropbox/load.py

      - name: publish
        run: |
          make publish

      - name: git
        run: |
          git checkout -b pr
          git add -f ${{github.workspace}}/site
          git commit -m "deployed at $(date)"
          git status
