name: deploy
on: [push]
defaults:
  run:
    working-directory: ./
jobs:
  necokecteni:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python dependencies
        run: |
          sed -i '/pkg-resources/d' requirements.txt
          pip install -r requirements.txt
          cd bin/dropbox
          mv settings.py.sample settings.py

      - name: install js dependencies
        run: npm install

      - name: extract
        env:
          PELICAN_TEMP_FOLDER: ${{secrets.PELICAN_TEMP_FOLDER}}
          PELICAN_CONTENT_FOLDER: ${{secrets.PELICAN_CONTENT_FOLDER}}
          DROPBOX_TOKEN: ${{secrets.DROPBOX_TOKEN}}
          DROPBOX_FOLDER_ID: ${{secrets.DROPBOX_FOLDER_ID}}
        run: |
          cd bin/dropbox
          ./extract.py

      - name: load
        env:
          PELICAN_TEMP_FOLDER: ${{secrets.PELICAN_TEMP_FOLDER}}
          PELICAN_CONTENT_FOLDER: ${{secrets.PELICAN_CONTENT_FOLDER}}
          DROPBOX_TOKEN: ${{secrets.DROPBOX_TOKEN}}
          DROPBOX_FOLDER_ID: ${{secrets.DROPBOX_FOLDER_ID}}
        run: |
          cd bin/dropbox
          ./load.py
          ls -l ../../content

      - name: publish
        run: make publish
