name: deploy
on: [push]
defaults:
  run:
    working-directory: ./
jobs:
  necokecteni:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python dependencies
        run: |
          sed -i '/pkg-resources/d' requirements.txt
          pip install -r requirements.txt
          cd bin/dropbox
          mv settings.py.sample settings.py

      - name: install js dependencies
        run: npm install

      - name: extract
        env:
          PELICAN_TEMP_FOLDER: ${{secrets.PELICAN_TEMP_FOLDER}}
          PELICAN_CONTENT_FOLDER: ${{secrets.PELICAN_CONTENT_FOLDER}}
        run: |
          cd bin/dropbox
          ls -l
          ./extract.py
