name: deploy
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python dependencies
        run: |
          ls -l
          sed -i '/pkg-resources/d' requirements.txt
