name: deploy
on: [push]
jobs:
  setup:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python dependencies
        run: |
          sed -i '/pkg-resources/d' requirements.txt
          pip install -r requirements.txt
          cd bin/dropbox
          mv settings.py.sample settings.py

      - name: install js dependencies
        run: npm install

  etl:
    defaults:
      run:
        working-directory: ./bin/dropbox
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: extract
        run: ./extract.py
